/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oggeyman_Oggeyman */
#ifndef JNI_VERSION_1_8
#define JNI_VERSION_1_8 0x00010008
#endif

#ifndef _Included_oggeyman_Oggeyman
#define _Included_oggeyman_Oggeyman
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oggeyman_Oggeyman
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_oggeyman_Oggeyman_create
  (JNIEnv *, jobject);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    init
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_oggeyman_Oggeyman_init
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    timer_restart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_oggeyman_Oggeyman_timer_1restart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    fast_forward_to_frame
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_oggeyman_Oggeyman_fast_1forward_1to_1frame
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_oggeyman_Oggeyman_width
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_oggeyman_Oggeyman_height
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    get_next_frame
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_oggeyman_Oggeyman_get_1next_1frame
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    done
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_oggeyman_Oggeyman_done
  (JNIEnv *, jobject, jlong);

/*
 * Class:     oggeyman_Oggeyman
 * Method:    shutdown
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_oggeyman_Oggeyman_shutdown
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
